version: "3.4"

services:
    
    jenkins:
        image: jenkins/jenkins
        ports:
            - "8999:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
        networks:
            ci: {}
        restart: no
    
    sonarqube:
        image: sonarqube
        ports:
            - "9000:9000"
            - "9092:9092"
        environment:
            SONARQUBE_JDBC_USERNAME: sonar
            SONARQUBE_JDBC_PASSWORD: sonar
            SONARQUBE_JDBC_URL: "jdbc:postgresql://sonar-db/sonar"
        volumes:
            - sonar_home:/opt/sonarqube/data
        networks:
            ci: {}
        depends-on:
            - sonar-db
        restart: no
    
    sonar-postgres:
        image: "postgres:10"
        environment:
            POSTGRES_DB: sonar
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - sonar_db:/var/lib/postgresql/data
        networks:
            ci: {}
        restart: no

volumes:
    jenkins_home:
    sonar_home:
    sonar_db:

networks:
    ci:
    