version: "3.4"

services:
    
    jenkins:
        image: jenkins/jenkins
        ports:
            - "8000:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
        networks:
            network: {}
    
    sonarqube:
        image: sonarqube
        ports:
            - "9000:9000"
            - "9092:9092"
        environment:
            SONARQUBE_JDBC_USERNAME: sonar
            SONARQUBE_JDBC_PASSWORD: sonar
            SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres/sonar"
        volumes:
            - sonar_home:/opt/sonarqube/data
        networks:
            network: {}
        depends_on:
            - postgres
    
    postgres:
        image: "postgres:10"
        environment:
            POSTGRES_DB: sonar
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - sonar_db:/var/lib/postgresql/data
        networks:
            network: {}

volumes:
    jenkins_home:
    sonar_home:
    sonar_db:

networks:
    network:
    